name: Coverage Report

on:
  push:
    branches: [ module, master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:

    - name: â• Check out Repository
      uses: actions/checkout@v2

    - name: ğŸ’¥ Set up Node.js
      run: sudo apt-get update && curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs libgbm-dev

    - name: ğŸ’¾ Add Package Dependencies
      run: yarn --frozen-lockfile

    - name: âš ï¸ ESLint Check
      run: yarn lint

    - name: ğŸ©º Unit Tests
      run: yarn test:ci
      env:
        CI: true

    - name: ğŸ“¡ Share Coverage Report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage-final.json